### ISSUE TITLE
Code vs. Community

### ISSUE THREAD

**Issue by Coirt** [cschol/vcv-rack-vscode#1]
Hi cs. I use VS community is VS code better for development of rack what advantages are there using code and the settings provided, have both. Find VS community a little easy to navigate and reference other code as you can add a file to the solution. New to both though.

Intellisense is in community is Code completion not sure. What way does it complete code? Tab. Use the peak in the nav pane quite a bit not sure if that is in code.

**Comment by cschol** [comment]
Hi Coirt. I am not familiar with VC Community, so I am not sure what the differences are. Here is a [link](https://code.visualstudio.com/docs/editor/intellisense) that shows what Intellisense does in Visual Studio Code. It works well enough for my purposes.
